version: 2

models:
  - name: dim_empleados
    description: "Dimensión con información detallada de los empleados activos."
    columns:
      - name: id_empleado
        tests:
          - unique
          - not_null

  - name: fct_ausentismo
    description: "Tabla de hechos de ausentismo laboral."
    columns:
      - name: id_ausencia
        tests:
          - unique
          - not_null
      - name: id_empleado
        tests:
          - relationships:
              to: ref('dim_empleados')
              field: id_empleado

  - name: fct_capacitacion
    description: "Tabla de hechos sobre capacitaciones realizadas por empleados."
    columns:
      - name: id_capacitacion
        tests:
          - unique
          - not_null
      - name: id_empleado
        tests:
          - relationships:
              to: ref('dim_empleados')
              field: id_empleado

  - name: fct_dotacion
    description: "Métrica de dotación total de empleados activos por área y género."
